spring:
  config:
    activate:
      on-profile: local
  cors:
    allowed-origins:
      - http://localhost:3000
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
  datasource:
    url: jdbc:postgresql://localhost:5432/yootaekstudy
    username: yootaek
    password: 2580
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      port: 6379
      host: localhost
