spring:
  profiles:
    active: local
    group:
      local: local, common
      blue: blue, common
      green: green, common

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  serverAddress: localhost

serverName: localhost

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
  serverAddress: 15.164.246.46

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081
  serverAddress: 15.164.246.46

serverName: green_server

---

spring:
  config:
    activate:
      on-profile: common
  application:
    name: study
  datasource:
    url: jdbc:postgresql://localhost:5432/yootaekstudy
    username: yootaek
    password: 2580
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      port: 6379
      host: localhost

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

jwt:
  secret_key: yootaekSecretKey!@
  access_expiration_time: 3600000
  reflesh_expiration_time: 10000000
  token_prefix: Bearer
  header_string: Authorization
