spring:
  config:
    activate:
      on-profile: local
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins:
              - http://localhost:3000
            allowed-headers: "*"
            allowed-methods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
  datasource:
    url: jdbc:postgresql://localhost:5432/yootaekstudy
    username: yootaek
    password: 2580
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      port: 6379
      host: localhost
