spring:
  application:
    name: study

  datasource:
    url: jdbc:postgresql://localhost:5432/yootaekstudy
    username: yootaek
    password: 2580
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

server:
  port: 443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: 258025
    key-store-type: PKCS12
    key-alias: selfsigned